version: '3'

services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped

    ports:
      - $DB_PORT:5432

    environment:
      POSTGRES_USER     : $DB_USER
      POSTGRES_PASSWORD : $DB_PASS
      POSTGRES_DB       : $DB_NAME

    volumes:
      - ./.container-volume:/var/lib/postgresql/data  # persist postgres data ref. https://stackoverflow.com/a/41650891/248616

    container_name : $DB_CONTAINER_NAME
    hostname       : $DB_CONTAINER_NAME

    networks:
      - docker_network_registry

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin/
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres


volumes:
  v_postgres:
    driver: local
  pgadmin:
    driver: local

