#TODO add ref. here
version: '2.0'

services:
  postgres:
    image: mdillon/postgis  # postgres image with postgis ready
    ports:
      - "54322:5432"  # note we double the last digit 2 on purpose to create our port - we aim not to overwrite the original port
    container_name: bxd_postgres
    volumes:
      - v_postgres:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin/
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres


volumes:
  v_postgres:
    driver: local
  pgadmin:
    driver: local

